### ISSUE TITLE
can't install docker. Will it also work an other way?

### ISSUE THREAD

**Issue by protected22** [guillaumebriday/laravel-blog#21] opened 2018-04-11 15:02 UTC
I can't install docker. So is there also an other way to use this blog system?

**Comment by guillaumebriday** [comment] 2018-04-11 15:42
Hey !

Yep there is another way but before we could try to find why docker isn't working on your system.

What's the error ?

**Comment by guillaumebriday** [comment] 2018-04-11 15:43
I close the issue because it's not a bug I think.

**Closed by guillaumebriday** 2018-04-11 15:43 UTC
Labels: invalid
